### ISSUE TITLE
Dont work 

### ISSUE THREAD

**Issue by emilsvfx** [walles/find_bad_motion_tracks#2]
Testing on Blender 2.93.1

Python: Traceback (most recent call last):
  File "C:\Users\EMILSVFX\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\find_bad_tracks-0_0_2.py", line 258, in draw
    row.template_list(
TypeError: UILayout.template_list(): error with keyword argument "active_dataptr" -  Function.active_dataptr does not support a 'None' assignment AnyType type

location: <unknown location>:-1

**Comment by walles** [comment]
Hey Emils!

Do you have any repro instructions for this? Can you tell me how to provoke this crash?

I have just fixed a number of issues, and this crash shouldn't be possible any more, but since I don't know how to reproduce it I can't say for sure that it's really fixed.

**Comment by walles** [comment]
I made a new release with my fixes, if you could verify this prevents your crash that would be super!

<https://github.com/walles/find_bad_motion_tracks/releases/tag/0.0.3>

**Comment by emilsvfx** [comment]
Hi, tracked footage and then just press button

**Comment by walles** [comment]
Then I'll just cross my fingers and hope the new [release 0.0.3](https://github.com/walles/find_bad_motion_tracks/releases/tag/0.0.3) works better for you.

Thanks for reporting Emils, I really appreciate it!
