### ISSUE TITLE
dont show up in UI

### ISSUE THREAD

**Issue by emilsvfx** [walles/find_bad_motion_tracks#3]
dont show up in UI

https://user-images.githubusercontent.com/22729351/129393350-093e5edb-1062-4590-8b13-d3afb80beb07.mp4

**Comment by walles** [comment]
Urgh.

Have you tried quitting Blender and starting it again?

When I toggle that button it works for me, not sure how to troubleshoot this :(.

I'm on Blender 2.93.2 now.

**Comment by semagnum** [comment]
@emilsvfx go up to Window->Toggle System Console and do the uncheck and check. That's where you'll be able to see any logs that could be useful.

**Comment by emilsvfx** [comment]
dont show up 


https://user-images.githubusercontent.com/22729351/129399987-e4678e66-5a23-4bd6-9d36-67d1549015b0.mp4

**Comment by walles** [comment]
@emilsvfx If you just add a cube to the 3D editor that should work around this problem, I can repro now.

Obviously having a 3D object shouldn't be necessary for tracking, and I intend to fix this, but adding that cube should enable you to use the plugin until I have a proper fix.

---

The problem with the current code...

https://github.com/walles/find_bad_motion_tracks/blob/ee88cf0a07984b00f6b119975b3d754b183b00c6/__init__.py#L258-L261

... is that if you have no 3D objects, the `context.object` will be `None` in `poll()`. And `context.object` is where I store my data.

And the obvious fix is for me to store my data somewhere else, I'll figure out where and make a new release.

But until then, just add a 3D cube and you should be good to go.

**Comment by emilsvfx** [comment]
yes looks like this workaround is working :)

**Comment by walles** [comment]
Just released 0.0.4 which shouldn't have this problem any more: <https://github.com/walles/find_bad_motion_tracks/releases/tag/0.0.4>

Thanks for reporting Emils!

Just out of curiosity, where did you find out about this add-on? Blendernation or somewhere else?

**Comment by emilsvfx** [comment]
Your welcome
i accidentally found in Blendernation

**Comment by semagnum** [comment]
Is this issue still open, or should it be closed?

**Comment by walles** [comment]
It should have been closed long ago, thanks for the heads up @semagnum!
